import Head from "next/head";

export default function Test() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Test</h1>
      <a href="/blog/test/test2">To test 2 page (without slash)</a>
    </>
  );
}
